<?php
    
?>
<?php
echo $this->partial('partials/header.pageDetails.phtml', array(
    'pageTitle' => str_replace("%CATEGORY_NEWS_NAME%", $this->categoryName, $this->getCibleText('header_list_news_text')),
    'pageDescription' => str_replace("%CATEGORY_NEWS_NAME%", $this->categoryName, $this->getCibleText('header_list_news_description')),
    'breadcrumb' => ''
));
?>

<div id="default_form">
    <div id="form_panel">
        <?php echo($this->mylist->render()); ?>        
    </div>                    
</div>