<?php
echo $this->partial('partials/header.pageDetails.phtml', array(
    'pageTitle' => $this->getCibleText('header_edit_administrator_group_text'),
    'pageDescription' => $this->getCibleText('header_edit_administrator_group_description'),
    'breadcrumb' => ''
));                
?>

<div id="default_form">
    <div id="form_panel">
        <?php echo($this->form);?>
    </div>                
</div>