<script>
    $(document).ready(function() {
        $("#<?php echo $this->imgPrev ?>").load(function(){
            var imageUrl = $("#imageUrl").val();
            if($(this).attr('src') != imageUrl){
                $("#isNewImage").val('true');
            }
        });
    });
</script>
<input type="hidden" id="imageUrl" value="<?php echo($this->imageUrl) ?>"/>
<?php
echo $this->partial('partials/header.pageDetails.phtml', array(
    'pageTitle' => $this->getCibleText('header_edit_categories_text'),
    'pageDescription' => $this->getCibleText('header_edit_categories_description'),
    'breadcrumb' => ''
));
?>

<div id="default_form">
    <div id="form_panel">
        <?php echo $this->form ?>
    </div>
</div>