<?php
echo $this->partial('partials/header.pageDetails.phtml', array(
    'pageTitle' => $this->getCibleText('extranet_profile_modify_link'),
    'pageDescription' => $this->getCibleText('extranet_profile_modify_link_description'),
    'breadcrumb' => ''
));                
?>

<div id="default_form">
    <div id="form_panel">
        <?php echo($this->form);?>        
    </div>                    
</div>