<?php
echo $this->partial('partials/header.pageDetails.phtml', array(
    'pageTitle' => $this->getCibleText('header_edit_newsletter_filter_collection_text'),
    'pageDescription' => $this->getCibleText('header_edit_newsletter_filter_collection_description'),
    'breadcrumb' => ''
));

echo($this->partial('partials/filters.add-update.phtml', array(
    'form'=>$this->form,
    'filterOptionsData'=>$this->filterOptionsData,
    'filterSetArray'=>$this->filterSetArray
)));