<?php
echo $this->partial('partials/header.pageDetails.phtml', array(
    'pageTitle' => $this->getCibleText('header_list_newsletter_filter_collection_text'),
    'pageDescription' => $this->getCibleText('header_list_newsletter_filter_collection_description'),
    'breadcrumb' => ''
));                
?>
<div id="default_form">
    <div id="form_panel">
        <?php echo($this->mylist->render()); ?>        
    </div>                    
</div>