<?php
    $form = $this->form;
?>

<?php
echo $this->partial('partials/header.pageDetails.phtml', array(
    'pageTitle' => $this->getCibleText('header_add_profile_text'),
    'pageDescription' => $this->getCibleText('header_add_profile_description'),
    'breadcrumb' => ''
));
?>

<div id="default_form">
    <div id="form_panel">
        <?php echo $form; ?>
    </div>
    <?php
    $hidden = 'class="hidden"';
    $href = '#';
    if ($this->displayError){
        $hidden = "";
        $href = $this->link;
    }
    ?>
    <a href="<?php echo $href; ?>" <?php echo $hidden; ?>>
        <p id="searchAgain" class="blueish-button">
            <?php echo $this->getCibleText('button_modify_existing_profile'); ?>
        </p>
    </a>
</div>
<?php //echo $this->partial('partials/js.GenericFormValidate.phtml', array('view' => $this)); ?>