<?php

    $event  = $this->event;
    //print_r($event);
?>
<div id="container_middle_full">
<?php
    if ($event):
?>      <h3><?php echo($event['Title']) ?></h3>
        <p>Êtes-vous sûr de vouloir supprimer l'événement <em><b><?php echo($event['Title']); ?></b></em>?</p>
        <form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
            <div>
                <input type="hidden" name="blockID" value="<?php echo $event['Title']?>" />
                <input type="submit" name="delete" value="<?php echo $this->getCibleText('button_yes') ?>" />
                <input type="submit" name="cancel" value="<?php echo $this->getCibleText('button_no') ?>" />
            </div>
        </form>
<?php
    else:
?>      <p>Cette événement est inexistant</p>
        <a href="<?php echo ($this->return); ?>">Retour</a>

<?php
    endif;
?>
</div>