<?php $other = (!empty($this->data[0])) ? $this->data[0]['subscribe'] : 0; ?>
<?php $total = $other; ?>
<table id="subscribe">
    <thead>
        <tr>
            <th class="sorting"><?php echo $this->getCibleText('newsletter_statistic_categories_label'); ?></th>
            <th class="sorting center"><?php echo $this->getCibleText('newsletter_statistic_total_label'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->data as $key => $value): ?>
            <?php if ($key > 0): ?>
            <tr id="nl-<?php echo $key; ?>">
                <td class="borders first"><?php echo $value['CI_Title']; ?></td>
                <td class="borders center last">
                    <span class="subscribe modalDetails" title="<?php echo $this->getCibleText('newsletter_statistic_subscribe_title'); ?> <?php echo $value['CI_Title']; ?>">
                    <?php echo $value['subscribe']; ?>
                    </span>
                </td>
            </tr>
            <?php $total += $value['subscribe']; ?>
            <?php endif; ?>
        <?php
        endforeach;
        ?>
    </tbody>
    <tfoot>
            <tr>
                <th class="bold borders first"><?php echo $this->getCibleText('newsletter_statistic_total_label'); ?></th>
                <th class="borders center last"><?php echo $total; ?></th>
            </tr>
    </tfoot>
</table>