<?php
echo $this->partial('partials/header.pageDetails.phtml', array(
    'pageTitle' => $this->getCibleText('header_list_administrator_groups_text'),
    'pageDescription' => $this->getCibleText('header_list_administrator_groups_description'),
    'breadcrumb' => ''
));                
?>

<div id="default_form">
    <div id="form_panel">
        <?php
            //echo($this->htmltable); 
            echo($this->mylist->render());
        ?>        
    </div>                    
</div>