<?php
echo $this->partial('partials/header.pageDetails.phtml', array(
    'pageTitle' => $this->getCibleText('header_delete_newsletter_article_title'),
    'pageDescription' => $this->getCibleText('header_delete_newsletter_article_description')
    //'breadcrumb' => Cible_FunctionsPages::buildTextBreadcrumb($this->pageId)
));                
?>
<?php $newsletterArticle  = $this->newsletterArticle; ?>
<div id="container_middle_full">    
<?php if ($newsletterArticle): ?>                  
        <h3><?php echo($newsletterArticle['NA_Title']) ?></h3>
        <p><?php echo str_replace('%ELEMENT_TITLE%', $newsletterArticle['NA_Title'], $this->getCibleText('module_delete_message_confirmation')) ?></p>
        <form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
            <div>
                <input type="submit" name="delete" value="<?php echo $this->getCibleText('button_yes') ?>" />
                <input type="submit" name="cancel" value="<?php echo $this->getCibleText('button_no') ?>" />
            </div>
        </form>
<?php else: ?>
        <p><?php echo $this->getCibleText('module_element_nout_found') ?></p>
        <a href="<?php echo ($this->return); ?>"><?php echo $this->getCibleText('button_return') ?></a>
<?php endif; ?>          
</div>


<?php
/*
    if( $this->isXmlHttpRequest ){
        if($this->deleted){
            if($this->success){
?>              <div id="result">
                    <span id="action" style="display: none">deleteArticle</span>
                    <span id="success" style="display: none">true</span>
                    <span id="articleID" style="display: none"><?php echo $this->articleID ?></span>
                </div>                
<?php       }
            else{
?>              <p>Cet article n'existe plus dans le système</p>
                <form enctype="application/x-www-form-urlencoded" method="post" action="">
                    <div>
                        <input type="submit" id="delete" name="delete" value="OK" />
                    </div>
                </form>
<?php       }
        }
        elseif( $this->success ){
?>          <div id="result">
                <span id="action" style="display: none">deleteArticle</span>
                <span id="success" style="display: none">true</span>
                <span id="articleID" style="display: none"><?php echo $this->articleID ?></span>
            </div>                            
<?php   }
        else{
?>          <div id="container_middle_full">    
<?php           if ($newsletterArticle):
?>                  <h3><?php echo($newsletterArticle['NA_Title']) ?></h3>
                    <p><?php echo str_replace('%ELEMENT_TITLE%', $newsletterArticle['NA_Title'], $this->getCibleText('module_delete_message_confirmation')) ?></p>
                    <form enctype="application/x-www-form-urlencoded" method="post" action="">
                        <div style="padding-bottom:25px">
                            <input type="submit" name="delete" value="<?php echo $this->getCibleText('button_yes') ?>" />
                            <button id="cancel" name="cancel" type="button"><?php echo $this->getCibleText('button_no') ?></button>
                        </div>
                    </form>
<?php           else: ?>
                    <p><?php echo $this->getCibleText('module_element_nout_found') ?></p>
                    <a href="<?php echo ($this->return); ?>"><?php echo $this->getCibleText('button_return') ?></a>
<?php           endif;
?>          </div>
<?php   }
    }
*/
?>