<?php
$this->headLink()->appendStylesheet($this->locateFile('jquery.autocomplete.css', null, 'front'));
$script = '<script type="text/javascript" src=' . $this->locateFile('jquery.autocomplete.pack.js', 'jquery', 'front') . '></script>';
$this->placeholder('footerScript')->set($script);
?>
<script type="text/javascript">
/*
 * Autocomplete actions.
 * Autocomplete field for the cities
 */
$(document).ready(function(){
//<![CDATA[
    var baseUrl = "<?php echo $this->baseUrl() ?>";
    var langId = <?php echo Zend_Registry::get('languageID')?>;

    var url    = baseUrl + "/default/index/ajax/actionAjax/citiesList";

    $('#addressFact-A_CityTextValue').autocomplete(url);
    $('#addressShipping-A_CityTextValue').autocomplete(url);
//]]>
})
</script>