<?php if ($this->pageCount > 1): ?>

    <?php  
    
        // images
        $_first_img = $this->first_link_image ? $this->first_link_image : $this->image("{$this->baseUrl()}/icons/paging_first.png", array('border'=> 0));
        $_prev_img = $this->prev_link_image ? $this->prev_link_image : $this->image("{$this->baseUrl()}/icons/paging_prev.png", array('border'=> 0));
        
        $_next_img = $this->next_link_image ? $this->next_link_image : $this->image("{$this->baseUrl()}/icons/paging_next.png", array('border'=> 0));
        $_last_img = $this->last_link_image ? $this->last_link_image : $this->image("{$this->baseUrl()}/icons/paging_last.png", array('border'=> 0));
    
    ?>

    <div class="paginationControl">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->url(array('page' => $this->first)); ?>"><?php echo $_first_img ?></a>&nbsp;&nbsp;
            <a href="<?php echo $this->url(array('page' => $this->previous)); ?>"><?php echo $_prev_img ?></a>&nbsp;&nbsp;
        <?php else: ?>
            <!--<span class="disabled"><?php echo $this->getCibleText('form_paginator_previous') ?></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-->
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?php echo $this->url(array('page' => $page)); ?>" class="paginator_link_page_number"><?php echo $page; ?></a>
            <?php else: ?>
                <span class="paginator_link_page_number selected"><?php echo $page; ?></span>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            &nbsp;&nbsp;<a href="<?php echo $this->url(array('page' => $this->next)); ?>"><?php echo $_next_img ?></a>
            &nbsp;&nbsp;<a href="<?php echo $this->url(array('page' => $this->last)); ?>"><?php echo $_last_img ?></a>
        <?php else: ?>
            <!--&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="disabled"><?php echo $this->getCibleText('form_paginator_next') ?></span>-->
        <?php endif; ?>
    </div>
<?php endif; ?>