<div id="lostPasswordPanel" style="display: none">
    <div id="lostPasswordPanel-content">
        <div id="request-form">
            <?php echo $this->getClientText('login_form_email_label') ?>&nbsp;<?php echo $this->formText('lostPasswordEmail', '', array('class'=>'loginTextInput')) ?><br />&nbsp;<?php echo $this->formButton('lostPasswordButton', '', array('class'=>'recoverButton-'. Zend_Registry::get("languageSuffix"), 'onclick'=>'javascript:retrievePassword();')) ?>
        </div>
        <div id="emailValidatorEmpty" class="errors"><?php echo $this->getCibleText('validation_message_empty_field') ?></div>
        <div id="emailValidatorError" class="errors"><?php echo $this->getClientText('lost_password_email_validation_error') ?></div>
        <div id="systemError" class="errors"></div>
    </div>
</div>