<?php  $gallery  = $this->gallery; ?>

<?php
    if( $this->isXmlHttpRequest ){
        if( $this->success ){
?>          <div id="result">
                <span id="action" style="display: none">deleteGallery</span>
                <span id="success" style="display: none">true</span>
                <span id="galleryID" style="display: none"><?php echo $this->galleryID ?></span>
                <span id="galleryDel" style="display: none"><?php echo $this->deleted ?></span>
            </div>
<?php   }
        else{
?>          <div id="container_middle_full">
<?php           if ($gallery):
?>                  <h3><?php echo($gallery['GI_Title']) ?></h3>
                    <p><?php echo str_replace('%ELEMENT_TITLE%', $gallery['GI_Title'], $this->getCibleText('module_delete_message_confirmation')) ?></p>
                    <!--<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">-->
                    <form enctype="application/x-www-form-urlencoded" method="post" action="">
                        <div>
                            <input type="submit" id="delete" name="delete" value="<?php echo $this->getCibleText('button_yes') ?>" />
                            <!--<input type="button" id="cancel" name="cancel" onclick="document.location.href='<?php echo($this->return); ?>'" value="<?php echo $this->getCibleText('button_no') ?>" />-->
                            <button id="cancel" name="cancel" type="button"><?php echo $this->getCibleText('button_no') ?></button>
                        </div>
                    </form>
<?php           else: ?>
                    <p><?php echo $this->getCibleText('module_element_nout_found') ?></p>
                    <a href="<?php echo ($this->return); ?>"><?php echo $this->getCibleText('button_return') ?></a>
<?php           endif; ?>
            </div>
<?php   }
    }
?>
