<?php
echo $this->partial('partials/header.pageDetails.phtml', array(
    'pageTitle' => $this->getCibleText('header_list_static_text_text'),
    'pageDescription' => $this->getCibleText('header_list_static_text_description'),
    'breadcrumb' => ''
));                
?>

<div id="default_form_no_position">
    <div id="form_panel">
        <?php echo($this->mylist->render()); ?>        
    </div>                    
</div>