<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){       
        
        $("a[rel^='prettyPhoto']").prettyPhoto({                
            show_title:true,
            animation_speed:'normal',
            theme:'facebook',
            slideshow:false, 
            autoplay_slideshow: false,
            overlay_gallery:false
        });
        
    });
</script>