<?php
    $genericMemberDetails  = $this->genericMemberDetails;
    
    echo $this->partial('partials/header.pageDetails.phtml', array(
    'pageTitle' => $this->getCibleText('header_delete_profile_text'),
    'pageDescription' => $this->getCibleText('header_delete_profile_description'),
    'breadcrumb' => ''
));                
?>
<div id="default_form">
<?php
    if ($genericMemberDetails):
?>      <h3><?php echo($genericMemberDetails['firstName']) ?>&nbsp;<?php echo($genericMemberDetails['lastName']) ?></h3>

        <p><?php echo str_replace('%MEMBER_NAME%', "<i><b>".$genericMemberDetails['firstName']." ".$genericMemberDetails['lastName']."</b></i>", $this->getCibleText('profile_delete_message_confirmation')) ?></p>
        <form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
            <div>
                <input type="submit" name="delete" value="<?php echo $this->getCibleText('button_yes') ?>" />
                <input type="submit" name="cancel" value="<?php echo $this->getCibleText('button_no') ?>" />
            </div>
        </form>
        
    <?php else: ?>
        <!--<p><?php echo $this->getCibleText('module_element_nout_found') ?></p>-->
        <a href="<?php echo ($this->return); ?>"><?php echo $this->getCibleText('button_return') ?></a>
    
<?php
    endif;
?>
</div>
