<?php $data = $this->emailRenderData; ?>
<html>
<head>
<meta http-equiv="content-language" content="fr">
<title>Clinique Lafontaine</title>

</head>
<body bgcolor="#FFFFFF" alink="#FFFFFF" vlink="#FFFFFF" link="#FFFFFF" text="#5D5D5C" topmargin="0" leftmargin="0" style="margin:0px;padding:0px;">

<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td align="center" valign="top">
            <table width="500" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td align="center" valign="top">
                        <?php echo $data['emailHeader']; ?>
                    </td>
                </tr>
                <tr>
                    <td height="10">&nbsp;</td>
                </tr>
                <tr>
                    <td align="left" valign="top" style="color: #5D5D5C; font-size:12px; font-family:arial">
                        <?php echo $data['message']; ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td height="10">&nbsp;</td>
    </tr>
    <tr>
        <td height="10" align="center" valign="middle" style="border-top:3px dotted #E2E2E2">&nbsp;</td>
    </tr>
    <tr>
        <td bgcolor="#BCBE00" height="35" align="center" valign="middle">
            <?php echo $data['footer']; ?>
        </td>
    </tr>
</table>
</body>
</html>