<?php
    $category  = $this->category;
?>
<div id="container_middle_full">    
<?php if ($category):?>
    <h3><?php echo($category['CCI_Name']) ?></h3>
        <p>
        <?php echo $this->getCibleText('delete_catalog_category_confirmation')?>
            <em><b><?php echo($category['CCI_Name']); ?></b></em>?
        </p>
        <form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
            <div>
                <input type="hidden" name="blockID" value="<?php echo $category['CCI_Name']?>" />
                <input type="submit" name="delete" value="<?php echo $this->getCibleText('button_yes') ?>" />
                <input type="submit" name="cancel" value="<?php echo $this->getCibleText('button_no') ?>" />
            </div>
        </form>
<?php else:?>
        <p><?php echo $this->getCibleText('delete_catalog_category_noexist')?></p>
        <a href="<?php echo ($this->return); ?>">
            <?php echo $this->getCibleText('button_return')?>
        </a>
    
<?php endif;?>
</div>