<?php $this->headStyle()->captureStart() ?>
    .block-rss .rss-feed {
        background: url(<?php echo $this->baseUrl() ?>/themes/default/images/common/rss_icon_small.png) no-repeat 0% 50%;
        padding-left: 20px;
    }
<?php $this->headStyle()->captureEnd() ?>

<div class="block block-rss">
    <?php  echo $this->link("{$this->baseUrl()}/rss/{$this->lang}/{$this->CategoryID}/rss.xml", $this->getCibleText('rss_news_subscribe'), array('class'=>'rss-feed','target'=>'_BLANK')); ?>
</div>