<?php
    
?>
<div id="login_form">
    <div id="login_form_header_left"></div>
    <div id="login_form_header_middle">
        <h1><?php echo $this->getCibleText('form_title_login') ?></h1>
    </div>
    <div id="login_form_header_right"></div>
    
    <div id="login_form_content">  
        <?php if( isset($this->error) ): ?>

            <p id="login_form_error"><?php echo $this->error ?></p>

        <?php endif; ?>
        
        <?php echo $this->form; ?>
        
    </div>
</div>